name: Build sbml_validator for macOS

on:
  workflow_dispatch:
  push:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download libSBML (macOS build)
        run: |
          curl -L -o libsbml.zip "https://github.com/sbmlteam/libsbml/releases/download/5.20.4/MacOS%20(zip,%20libSBML%205.20.4,%20all-packages)-2.zip"
          unzip libsbml.zip -d libsbml-mac

      - name: Build sbml_validator
        run: |
          clang++ sbml_validator.cpp -o sbml_validator_mac \
            -Ilibsbml-mac/include \
            -Llibsbml-mac/lib \
            -Wl,-rpath,@executable_path/../lib \
            -lsbml \
            -std=c++17

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: sbml_validator_mac
          path: sbml_validator_mac
