name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to Marketplace
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Volta
      uses: volta-cli/action@v4

    - name: Install dependencies
      run: npm ci

    - name: Package extension
      run: npx vsce package

    - name: Publish to Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: npx vsce publish

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract changelog for release
      id: changelog
      run: |
        TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        echo "Detected tag name: $TAG_NAME"
        
        CHANGELOG=$(awk "/## \[${TAG_NAME}\]/,/^## /" CHANGELOG.md | sed '$d')
        echo "Extracted changelog content:"
        echo "---"
        echo "$CHANGELOG"
        echo "---"
        
        echo "Setting changelog output..."
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "Changelog output has been set"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false