name: Run Tests

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Volta
      uses: volta-cli/action@v4

    - name: Install dependencies
      run: npm ci

    - name: Install xvfb on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Rebuild sbml_validator for macOS
      if: runner.os == 'macOS'
      run: |
        clang++ -std=c++11 -mmacosx-version-min=10.15 -o validator/mac/sbml_validator sbml_validator.cpp \
        -Lartifacts/MacOS-libSBML-5.20.4-stable-packages/lib -lsbml \
        -Iartifacts/MacOS-libSBML-5.20.4-stable-packages/include

    - name: Run tests
      if: runner.os != 'Linux'
      run: npm test
      env:
        DISPLAY: ':99.0'
        DYLD_LIBRARY_PATH: /Users/runner/work/sbml-linter/sbml-linter/artifacts/MacOS-libSBML-5.20.4-stable-packages/lib

    - name: Run tests on Linux
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test
      env:
        DISPLAY: ':99.0'

    - name: Run linting
      run: npm run lint