name: Run Tests

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Volta
      uses: volta-cli/action@v4

    - name: Install dependencies
      run: npm ci

    - name: Install xvfb on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run tests
      if: runner.os != 'Linux'
      run: npm test
      env:
        DISPLAY: ':99.0'

    - name: Run tests on Linux
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test
      env:
        DISPLAY: ':99.0'

    - name: Run linting
      run: npm run lint